import { Button } from './button'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  'https://www.figma.com/design/56EvebfAdgA7JaDIldZAFK/Green-Design-System-(v1)?node-id=2-178&t=GuycQdAmesJ2sTmD-4',
  {
    props: {
      secondarylabel: figma.string('Secondary label'),
      tertiarylabel: figma.string('Tertiary label'),
      primarylabel: figma.string('Primary label'),
      icon: figma.instance('Icon'),
      style: figma.enum('Style', {
        Normal: 'normal',
        Positive: 'positive',
        Negative: 'negative',
      }),
      prio: figma.enum('Prio', {
        Primary: 'primary',
        Secondary: 'secondary',
        Tertiary: 'tertiary',
        Te: 'te',
      }),
      size: figma.enum('Size', {
        Large: 'large',
        Medium: 'medium',
        Small: 'small',
      }),
      state: figma.enum('State', {
        Enabled: 'enabled',
        Hovered: 'hovered',
        Pressed: 'pressed',
        Disabled: 'disabled',
      }),
      iconplacement: figma.enum('Icon placement', {
        None: 'none',
        Left: 'left',
        Right: 'right',
      }),
    },
    example: (props) => <Button />,
  },
)
